/* Research harness. The production function is included byte-for-byte from
   the pinned ARM-software/CMSIS-NN upstream checkout, not reimplemented. */
#include <stdint.h>
#include <assert.h>
#include "arm_nnsupportfunctions.h"

#ifndef SIZE
#define SIZE 1
#endif

extern int32_t nd_i32(void);
extern int8_t nd_i8(void);

/* Independently coded, explicit floor-division oracle for CMSIS-NN
   SINGLE_ROUNDING, only over bounded inputs with no 64-bit overflow. */
static int32_t ref_requantize(int32_t value, int32_t multiplier, int32_t shift)
{
    int64_t divisor = (int64_t)1 << (31 - shift);
    int64_t numerator = (int64_t)value * multiplier + divisor / 2;
    int64_t rounded = (numerator >= 0) ? (numerator / divisor)
                     : -((-numerator + divisor - 1) / divisor);
    return (int32_t)rounded;
}

#ifdef COMPOSED
/* Generated by an exact replacement of five call sites from original source.
   Valid only if an independent PROVE_LEMMA run succeeds. */
static int32_t certified_ref(int32_t v, int32_t m, int32_t s)
{
    return ref_requantize(v, m, s);
}
#include "mul_composed.c"
#else
#include "arm_elementwise_mul_s8.c"
#endif

int main(void)
{
    int32_t multiplier = nd_i32();
    int32_t shift = nd_i32();
    __CPROVER_assume(multiplier == 536870912 || multiplier == 1073741824);
    __CPROVER_assume(shift >= -1 && shift <= 1);

#ifdef PROVE_LEMMA
    int32_t v = nd_i32();
    __CPROVER_assume(v >= -18500 && v <= 18500);
    assert(arm_nn_requantize(v, multiplier, shift) == ref_requantize(v, multiplier, shift));
#else
    int8_t a[SIZE];
    int8_t b[SIZE];
    int8_t out[SIZE];
    int32_t off1 = nd_i32();
    int32_t off2 = nd_i32();
    int32_t out_offset = nd_i32();
    __CPROVER_assume(off1 >= -8 && off1 <= 8);
    __CPROVER_assume(off2 >= -8 && off2 <= 8);
    __CPROVER_assume(out_offset >= -8 && out_offset <= 8);
    for (int i = 0; i < SIZE; ++i)
    {
        a[i] = nd_i8();
        b[i] = nd_i8();
        out[i] = 0;
    }
    arm_cmsis_nn_status status = arm_elementwise_mul_s8(a, b, off1, off2,
                                  out, out_offset, multiplier, shift,
                                  -100, 100, SIZE);
    assert(status == ARM_CMSIS_NN_SUCCESS);
    for (int i = 0; i < SIZE; ++i)
    {
        int32_t v = ((int32_t)a[i] + off1) * ((int32_t)b[i] + off2);
        int32_t expected = ref_requantize(v, multiplier, shift) + out_offset;
        if (expected < -100) expected = -100;
        if (expected > 100) expected = 100;
#ifdef MUTANT
        if (i == 0) expected ^= 1; /* deliberately invalid reference */
#endif
        assert((int32_t)out[i] == expected);
    }
#endif
    return 0;
}
